### ISSUE TITLE
Adding Lighthouse

### ISSUE THREAD

**Issue by aasignacion** [RoboticExplorationLab/tinympc-crazyflie-firmware#4]
Hello, Thank you for your work.
I would like to try it but it seems lighthouse is not integrated. 
Could you help integrate it?
Thank you.

**Comment by SoonBu** [comment]
Hello, can you please tell me how you solved this issue? In the directory: tinympc-crazyflie-firmware/src/drivers/src I have found the exact same lighthouse setting .c files as in the default crazyflie-firmware repository. But I still cant flash the lighthouse settings on my deck whenever I flash the tinympc controller on my crazyflie.
