### ISSUE TITLE
lh_flasher.c doens't get flashed on deck

### ISSUE THREAD

**Issue by SoonBu** [RoboticExplorationLab/tinympc-crazyflie-firmware#5]
Hello community,

I'm currently working with the crazyflie 2.1 and I try to flash the controller_tinympc on my crazyflie. I have a GAP8 deck connected on my crazyflie and now I want to flash the controller_tinympc on my crazyflie. 

When I flash the default firmware: https://github.com/bitcraze/crazyflie-firmware/tree/master. Then I have the default controllers and the lighthouse settings are uploaded to my deck aswell in order for me to use it. But when i flash the default firmware and then flash the controller_tinympc from the [tinympc-crazyflie-firmware](https://github.com/RoboticExplorationLab/tinympc-crazyflie-firmware)], my crazyflie gets the default firmware successfully but my deck is empty and there is no firmware flashed on it.

I tracked during the building steps of the "tinympc-crazyflie-firmware" the process of "make" and I noticed that the "lh_flasher.c" (tinympc-crazyflie-firmware/src/drivers/src/) doesn't get build. I have also done "make clean" -> "make". 

Can someone help me please?

**Comment by xkhainguyen** [comment]
Hi, you may want to enable the light house module (and some others) since we may disable it to save memory. 
[controller_tinympc_input_soc](https://github.com/RoboticExplorationLab/tinympc-crazyflie-firmware/tree/main/examples/controller_tinympc_input_soc) is one of the most recent examples that we tested.

**Comment by SoonBu** [comment]
Hi,
thank you for your fast reply. I'm still a beginner to all crazyflie functions. Can you tell me where I can set the light house module in the configs? (path to the file -> which line to adjust)

And I tried flashing the https://github.com/RoboticExplorationLab/tinympc-crazyflie-firmware/tree/main/examples/controller_tinympc_input_soc on my crazyflie 2.1 with its GAP8 deck on it but when I open the cfclient the console outputs me:

SYS: I am 0x203937434848500D0047003C and I have 1024KB of flash!
CFGBLK: v1, verification [OK]
DECK_INFO: Warning! No driver found for deck.
DECK_CORE: 1 deck(s) found
IMU: BMI088: Using I2C interface.
IMU: BMI088 Gyro connection [OK].
IMU: BMI088 Accel connection [OK]
IMU: BMP388 I2C connection [OK]
ESTIMATOR: Using Complementary (1) estimator
CONTROLLER: Using PID (1) controller
MTR-DRV: Using brushed motor driver
SYS: About to run tests in system.c.
SYS: NRF51 version: 2024.2 (CF21)
EEPROM: I2C connection [OK].
STORAGE: Storage check [OK].
IMU: BMI088 gyro self-test [OK]
SYS: Self test passed!
STAB: Wait for sensor calibration...
SYS: Free heap: 20504 bytes
MPC: Waiting for activation ...
STAB: Ready to fly.
STAB: WARNING: stabilizer loop rate is off (499)

The important part is "DECK_INFO: Warning! No driver found for deck." is there a setting in the configs to flash onto the deck or am I missing something?

**Comment by xkhainguyen** [comment]
Please check https://github.com/RoboticExplorationLab/tinympc-crazyflie-firmware/issues/6#issue-2417981573
