### ISSUE TITLE
DECK_INFO: Warning! No driver found for deck." issue 

### ISSUE THREAD

**Issue by jeongheonn** [RoboticExplorationLab/tinympc-crazyflie-firmware#6]
Hello! I have a question regarding the "DECK_INFO: Warning! No driver found for deck." issue.

I am using Crazyflie 2.1, Flow Deck v2, Crazyradio, and Lighthouse Positioning Deck. When using the crazyflie-firmware, there were no issues with deck detection, and it was confirmed in the console tab of the cfclient. https://github.com/bitcraze/crazyflie-firmware

However, when I make and make cload the example controller_tinympc_state_soc from the tinympc-crazyflie-firmware, I receive an error message indicating that the driver cannot be found. I have attached a related photo. I would like to know if there is anything additional that needs to be included when building the firmware to support the relevant driver. 

(Currently, the propellers of the Crazyflie are operating via the b_MPC.ipynb file in crazyflie-princeton, but I believe that the issue of not being able to lift off properly is due to the Flow Deck recognition problem.)

Thank you!

<crazyflie-firmware, with flow deck> -----> No problem detected
SYS: Crazyflie 2.1 is up and running!
SYS: Build 0:e527895e8c6e (2023.11) CLEAN
SYS: I am 0x203235324133501900420033 and I have 1024KB of flash!
CFGBLK: v1, verification [OK]
DECK_CORE: 1 deck(s) found
DECK_CORE: Calling INIT on driver bcFlow2 for deck 0
ZR2: Z-down sensor [OK]
PMW: Motion chip id: 0x49:0xB6
IMU: BMI088: Using I2C interface.
IMU: BMI088 Gyro connection [OK].
IMU: BMI088 Accel connection [OK]
IMU: BMP388 I2C connection [OK]
ESTIMATOR: Using Kalman (2) estimator
CONTROLLER: Using PID (1) controller
MTR-DRV: Using brushed motor driver
SYS: About to run tests in system.c.
SYS: NRF51 version: 2024.2 (CF21)
EEPROM: I2C connection [OK].
STORAGE: Storage check [OK].
IMU: BMI088 gyro self-test [OK]
DECK_CORE: Deck 0 test [OK].
SYS: Self test passed!
STAB: Wait for sensor calibration...
SYS: Free heap: 17608 bytes
STAB: Starting stabilizer loop
ESTKALMAN: State out of bounds, resetting
SUP: Can not fly
SUP: Ready to fly

<tinympc-crazyflie-firmware, with flow deck> -----> No driver found for deck 
SYS: Crazyflie 2.1 is up and running!
SYS: Build 0:5af0a2f189fe (NA) CLEAN
SYS: I am 0x203235324133501900420033 and I have 1024KB of flash!
CFGBLK: v1, verification [OK]
DECK_INFO: Warning! No driver found for deck.
DECK_CORE: 1 deck(s) found
IMU: BMI088: Using I2C interface.
IMU: BMI088 Gyro connection [OK].
IMU: BMI088 Accel connection [OK]
IMU: BMP388 I2C connection [OK]
ESTIMATOR: Using Complementary (1) estimator
CONTROLLER: Using PID (1) controller
MTR-DRV: Using brushed motor driver
SYS: About to run tests in system.c.
SYS: NRF51 version: 2024.2 (CF21)
EEPROM: I2C connection [OK].
STORAGE: Storage check [OK].
IMU: BMI088 gyro self-test [OK]
SYS: Self test passed!
STAB: Wait for sensor calibration...
SYS: Free heap: 20504 bytes
MPC: Waiting for activation ...
STAB: Ready to fly.
STAB: WARNING: stabilizer loop rate is off (501)

![image](https://github.com/user-attachments/assets/27af40f7-ef31-42d6-8891-063eb3facd4a)

**Comment by xkhainguyen** [comment]
1. Please enable your deck drivers at https://github.com/RoboticExplorationLab/tinympc-crazyflie-firmware/blob/main/src/deck/drivers/src/Kconfig by set `default n` to `default y`

2. Have you flied the drone with cfclient or `b_MPC.ipynb` and https://github.com/bitcraze/crazyflie-firmware?
