### ISSUE TITLE
Lighthouse orientation is drifting away!

### ISSUE THREAD

**Issue by SoonBu** [RoboticExplorationLab/tinympc-crazyflie-firmware#7]
Hello community,

I'm currently working with the crazyflie 2.1 and I flashed the controller_tinympc on my crazyflie. I have a GAP8 deck connected on my crazyflie. At first I have flashed the latest crazyflie firmware (https://github.com/bitcraze/crazyflie-release/releases) on my crazyflie+deck and started it in my lighthouse setup. Everything worked well and the orientation of my crazyflie was correct, thus I was able to let it fly.

But now I flashed the tinympc controller on my crazyflie and despite not getting any errors during the flashing process, whenever I put my crazyflie into the lighthouse setup my orientation is constantly moving (normally it should stand still if I just place it on the ground). Since it worked correctly with the latest firmware it shouldn't be a problem with my hardware setup but with the tinympc_controller. 

My steps: 
-  cd to direcrory "tinympc-crazyflie-firmware/src/deck/drivers/src/Kconfig"
- change line 243: change "default n" to "default y"
- cd to directory "home/tinympc-crazyflie-firmware/examples/controller_tinympc"
- make clean
- make
- hold crazyflie for 3s in order to enter bootloader
- make cload

Can you please help me?

**Comment by SoonBu** [comment]
I really need further help with this problem.

**Comment by xkhainguyen** [comment]
Please check your email for my response.
